### ISSUE TITLE
[제안] 개발환경에서 query explain 을 통한 프로파일링 자동화

### ISSUE THREAD

**Issue by namenu** [green-labs/honeysql-mysql#11]
1. honey.sql/format 을 alter-var-root 로 honey.sql.my/format 으로 치환

2. honey.sql.my/format 에서는 select 쿼리 인터셉트 & explain 쿼리를 tap> 으로 보냄

```clojure
;; honey.sql.my
(defn format [data opts]
  (tap> (honey.sql/format (merge data {:explain []}) opts)))
  (honey.sql/format data opts))
```

이 때, 중복된 쿼리는 필터링하고 옵션으로도 끌 수 있으면 좋겠음.

3. 프로파일러는 tap 에 들어오는 explain 쿼리를 jdbc/execute 해보고 리포트 생성

**Comment by SongKJ00** [comment]
요거 제가 작업해보겠습니다!!

**Comment by namenu** [comment]
구현하다보면 막히는 부분이 꽤 있을 것 같은데, 아이디어 해먹에 넣고 아키텍처를 먼저 그려보시는 것을 추천드립니다!

**Comment by SongKJ00** [comment]
넵! 말씀해주신대로 먼저 아키텍처를 그려보겠습니다 ㅎㅎ
감사합니다~!!

**Comment by duddlf23** [comment]
`tab>` 요런게 있군요 디버깅에 쏠쏠하네요!!

**Comment by SongKJ00** [comment]
@namenu 
작업하다가 한 가지 고민이 드는 부분이 있어서 코멘트 남깁니다!!

`honey.sql/format`을 `alter-var-root`로 `honey.sql.my/format`으로 치환하였을 때 무한 재귀가 생기면서 StackOverflowError가 발생하네요 😢

정확한 원인을 말씀드리자면 `honey.sql.my/format` 함수 body에 있는 `honey.sql/format`도 alter-var-root로 인해, `honey.sql.my/format`으로 치환되면서 계속해서 `honey.sql.my/format`을 콜하게 되는 구조입니다.
```clojure
;; honey.sql.my
(defn format [data opts]
  (tap> (honey.sql/format (merge data {:explain []}) opts))) ;; <= 이 부분도 결국 honey.sql.my/format 호출하면서 무한 재귀...
  (honey.sql/format data opts))
``` 
그래서, `honey.sql.my` ns에 대해서만은 `honey.sql/format`을 치환해서 사용되지 않도록 막아야 할 것 같은데 요 부분에 대한 아이디어가 잘 떠오르질 않습니다...

혹시 어떻게 접근하면 깔끔하게 해결할 수 있을까요...??

**Comment by SongKJ00** [comment]
⬆️ 추가적으로 조금 생각해보았는데, explain & 프로파일링하는 책임을 전부 백엔드 레포에 맡기면 어떨까요!!

이 `honeysql-mysql` 레포는 mysql vendor에 특화된 syntax에 대한 확장만 지원할 뿐이고,
explain을 이용한 프로파일링 함수 및 로직은 전부 저희 백엔드 레포(sinsunhi-backend)에서 구현하는 것이죠.

저희 백엔드에서 쿼리 날리는 함수인 `execute!` body에서 `tap>` 으로 explain을 추가한 쿼리를 보내면 어떨까 싶습니다!
그리고 이 `tap>` 으로 넘어온 explain 쿼리에 대한 프로파일링 로직은 user.clj안에서 구현하구요

제 아이디어를 코드로 옮기자면 아래와 같습니다..!
```clojure
(defn execute!
  [conn q option]
  (tap> (merge q {:explain []})) ;; => 이 라인만 추가
  (jdbc/execute! conn q option))
```

**Comment by namenu** [comment]
아... 저의 설익은 아이디어로 시간을 낭비하셨군요...

백엔드에서 직접 하는 방법도 물론 좋습니다! 🙌🏼

**Comment by namenu** [comment]
explain 결과에서 filesort 등과 같은 warning 을 감지하는 것이 중요하겠군요!

**Comment by duddlf23** [comment]
```clojure
;; honey.sql.my
(defn custom-format
  [format]
  (fn [data & args]
    (tap> (apply format (merge data {:explain []}) args))
    (apply format data args)))
```

근재님이 직면하신 무한재귀 문제는 요런 식으로 풀면 해결할 수 있을 듯 합니다!! `alter-var-root` 자체가 var의 원본 값을 인자로 받는 f를 필요로 합니다. & args로 한 이유는 `honey.sql/format`이 data만 첫 인자로 고정인 multi-arity function이기 때문입니당

**Comment by SongKJ00** [comment]
아하 영일님이 예제로 적어주신 `custom-format`처럼 아예 함수를 리턴하도록 구현하면 무한재귀에 빠지지 않겠네요..!!
`custom-format`에 인자로 들어오는 `format`이 원본인 `honey.sql/format`이니, `honey.sql.my/format`을 지속적으로 재귀호출하지도 않구요.

오늘도 영일님 덕분에 하나 알아갑니다.... 🙏 🙏

**Comment by SongKJ00** [comment]
> 아... 저의 설익은 아이디어로 시간을 낭비하셨군요...

앗 아닙니다!! 제가 너무 깊게 생각한 감이 있는 것 같아요... 
이번 미션의 본질인 `explain 결과에서 filesort 등과 같은 warning 을 감지하는 것`에 조금 더 집중을 해야겠습니다.
문제를 해결하는 데는 한 가지만 있는 게 아닌 여러가지 방법이 있는 것이니까요.. ㅎㅎ

**Comment by namenu** [comment]
오우 대단하십니다 진짜!
